services:
  # Mosquitto MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-broker
    ports:
      - "1883:1883"  # MQTT default port
      - "9001:9001"  # WebSocket port
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - mqtt-network
    restart: unless-stopped

  # NestJS Application
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-mqtt-app
    ports:
      - "3001:3000"  # Changed to 3001 to avoid port conflict
    environment:
      - MQTT_BROKER_URL=mqtt://mosquitto:1883
      - NODE_ENV=development
    depends_on:
      - mosquitto
    networks:
      - mqtt-network
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules

networks:
  mqtt-network:
    driver: bridge 